import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "./components/NavigationBar";
import localFont from "next/font/local";

const Sora = localFont({
  src: "../../public/Font/Sora-VariableFont_wght.ttf",
  variable: "--font-sora",
});

export const metadata: Metadata = {
  title: "Partner dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Sora.className}>
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}
